[server]
headless = true
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#e94560"
backgroundColor = "#0f0c29"
secondaryBackgroundColor = "#1a1a2e"
textColor = "#ffffff"
